name       : xfce4-screenshooter
version    : 1.10.4
release    : 1
source     :
    - https://archive.xfce.org/src/apps/xfce4-screenshooter/1.10/xfce4-screenshooter-1.10.4.tar.bz2 : a2f199687e54e16a936d5636d660d42b6b9a5d548cdd0f04bd69213554806494
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : An application to take screenshots for xfce.
description: |
    An application to take screenshots for xfce.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install
